version: '3.8'

services:
  web-text-forum:
    container_name: web-text-forum-c1
    build:
      context: .
      dockerfile: web-text-forum\Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=webtextforum_db;User Id=sa;Password=enforcement_nonillions_cadagis_01;TrustServerCertificate=True;

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=enforcement_nonillions_cadagis_01
      - MSSQL_PID=Developer